/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Clases.*;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class actualizarDatos extends javax.swing.JFrame {

    /**
     * Creates new form Modificar
     */
    public actualizarDatos() {
        initComponents();
        setLocationRelativeTo(null);
        txtCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                String cedula = txtCedula.getText().trim();
                if (!(cedula.isBlank())) {
                    buscarpaciente();  // Llamar al método cuando se pierde el foco
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtapellido = new javax.swing.JTextField();
        labelEdad = new javax.swing.JLabel();
        labelApellidos = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        labelEps = new javax.swing.JLabel();
        txtEps = new javax.swing.JTextField();
        labelId = new javax.swing.JLabel();
        bttActualizar = new javax.swing.JButton();
        txtNum = new javax.swing.JTextField();
        labelTelefono = new javax.swing.JLabel();
        txtRegistro = new javax.swing.JLabel();
        datosBasicos = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        bttRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        txtapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidoActionPerformed(evt);
            }
        });

        labelEdad.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelEdad.setText("Edad - #");

        labelApellidos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelApellidos.setText("Apellidos");

        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        labelEps.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelEps.setText("Eps");

        txtEps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEpsActionPerformed(evt);
            }
        });

        labelId.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelId.setText("N° Identificacion - #");

        bttActualizar.setText("Actualizar");
        bttActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttActualizarActionPerformed(evt);
            }
        });

        txtNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumActionPerformed(evt);
            }
        });

        labelTelefono.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelTelefono.setText("Numero De Telefono - #");

        txtRegistro.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtRegistro.setText("Modificar los datos");

        datosBasicos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        datosBasicos.setText("Datos Basicos");

        labelNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelNombre.setText("Nombre");

        txtnombre.setToolTipText("");
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        bttRegresar.setText("Regresar");
        bttRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datosBasicos, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelId)
                        .addGap(150, 150, 150)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTelefono)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEdad)))
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(labelEps))
                    .addComponent(txtEps, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(bttActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttRegresar)
                .addGap(117, 117, 117))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtRegistro)
                .addGap(139, 139, 139))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(datosBasicos)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelId)
                            .addComponent(labelNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelApellidos)
                            .addComponent(labelTelefono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEdad)
                            .addComponent(labelEps))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEps, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttActualizar)
                    .addComponent(bttRegresar))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidoActionPerformed
        txtNum.requestFocus();
    }//GEN-LAST:event_txtapellidoActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        txtEps.requestFocus();
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        txtnombre.requestFocus();
        buscarpaciente();
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumActionPerformed
        txtEps.requestFocus();
    }//GEN-LAST:event_txtNumActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        txtapellido.requestFocus();
    }//GEN-LAST:event_txtnombreActionPerformed

    private void bttRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRegresarActionPerformed

        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_bttRegresarActionPerformed

    private void bttActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttActualizarActionPerformed

        try {
            //Obtiene los datos de los textfield
            long cedula = Long.parseLong(txtCedula.getText());
            String nombre = txtnombre.getText();
            String apellido = txtapellido.getText();
            long numTelefono = Long.parseLong(txtNum.getText());
            int edad = Integer.parseInt(txtEdad.getText());
            String eps = txtEps.getText();

            //Valida que no haya datos en blanco
            if (nombre.isBlank() || apellido.isBlank() || eps.isBlank()) {
                JOptionPane.showMessageDialog(null, "No puedes dejar espacios en blanco");
                return;
            }

            boolean encontrado = false; // Bandera para validar si se encontro el paciente

            Nodo aux = turnos.getPrimero();
            while (aux != null) {
                Paciente pa = (Paciente) aux.getDato();
                if (pa.getCedula() == cedula) {
                    //Rellena los textfield con los datos encontrados
                    pa.setNombre(nombre);
                    pa.setApellido(apellido);
                    pa.setTelefono(numTelefono);
                    pa.setEdad(edad);
                    pa.setEps(eps);
                    encontrado = true;
                }
                aux = aux.getSiguiente();
            }

            if (encontrado) {
                JOptionPane.showMessageDialog(null, "Paciente actualizado.");
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró un paciente con esa cédula.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "En los campos con # digite solo números válidos.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Campos mal llenados.");
        }

    }//GEN-LAST:event_bttActualizarActionPerformed

    public void buscarpaciente() {
        try {
            long cedula = Long.parseLong(txtCedula.getText());
            Nodo aux = turnos.getPrimero();
            boolean encontrado = false;

            while (aux != null) {
                Paciente pa = (Paciente) (aux.getDato());
                if (pa.getCedula() == cedula) {
                    txtnombre.setText(pa.getNombre());
                    txtapellido.setText(pa.getApellido());
                    txtNum.setText(pa.getTelefono() + "");
                    txtEdad.setText(Integer.toString(pa.getEdad()));
                    txtEps.setText(pa.getEps());
                    encontrado = true;
                    break;
                }
                aux = aux.getSiguiente();
            }

            if (!encontrado) {
                JOptionPane.showMessageDialog(null, "No se encontró un paciente con esta cédula");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Campos mal llenados");
        }

    }


    private void txtEpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEpsActionPerformed
        // TODO add your handling code here:
        txtEdad.requestFocus();  // Pasa el foco a txtEdad
    }//GEN-LAST:event_txtEpsActionPerformed

    public void recibirColaPacientes(Cola cola) {
        //Recibe la cola de home
        turnos = cola;
    }

    public void recibirMenu(Home m) {
        //Recibe a Home
        menu = m;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(actualizarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(actualizarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(actualizarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(actualizarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new actualizarDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttActualizar;
    private javax.swing.JButton bttRegresar;
    private javax.swing.JLabel datosBasicos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelApellidos;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelEps;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEps;
    private javax.swing.JTextField txtNum;
    private javax.swing.JLabel txtRegistro;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
    Home menu;
    Cola turnos;
}
