package Ventanas;

import Clases.*;

import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
        // Instancias a las otras ventanas 
        registrar = new Registrar(this);
        consultarTurnos = new consultarTurnos(this);
        consultarHistorial = new consultarHistorialPaciente(this);
        historialAtendidos = new historialAtendidos(this);
        actualizarDatos = new actualizarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        labelHospital = new javax.swing.JLabel();
        bttConsultaTurnos = new javax.swing.JButton();
        bttRegistro = new javax.swing.JButton();
        bttAtendidosRecien = new javax.swing.JButton();
        bttConsultaPacientes = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnImportarexcel = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(51, 153, 255));
        Fondo.setPreferredSize(new java.awt.Dimension(400, 400));

        labelHospital.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelHospital.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHospital.setText("Hospital Jesus Angel");

        bttConsultaTurnos.setText("Consultar Turnos");
        bttConsultaTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttConsultaTurnosActionPerformed(evt);
            }
        });

        bttRegistro.setText("Registrar Pacientes");
        bttRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRegistroActionPerformed(evt);
            }
        });

        bttAtendidosRecien.setText("Atendidos");
        bttAtendidosRecien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAtendidosRecienActionPerformed(evt);
            }
        });

        bttConsultaPacientes.setText("Consultar Pacientes");
        bttConsultaPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttConsultaPacientesActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar Informacion");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnImportarexcel.setText("Importar");
        btnImportarexcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarexcelActionPerformed(evt);
            }
        });

        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(labelHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(bttAtendidosRecien))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bttConsultaTurnos)
                            .addComponent(bttConsultaPacientes)
                            .addComponent(bttRegistro)))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizar)
                            .addGroup(FondoLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnImportarexcel)
                                    .addComponent(btnExportar))))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(labelHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(bttRegistro)
                .addGap(27, 27, 27)
                .addComponent(bttConsultaTurnos)
                .addGap(28, 28, 28)
                .addComponent(bttAtendidosRecien)
                .addGap(28, 28, 28)
                .addComponent(bttConsultaPacientes)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar)
                .addGap(18, 18, 18)
                .addComponent(btnImportarexcel)
                .addGap(18, 18, 18)
                .addComponent(btnExportar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRegistroActionPerformed
        // TODO add your handling code here:
        registrar.recibirTurnos(turnos);
        registrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bttRegistroActionPerformed

    private void bttConsultaTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttConsultaTurnosActionPerformed
        // TODO add your handling code here:
        consultarTurnos.recibirPila(atendidos);
        consultarTurnos.recibirCola(turnos);
        consultarTurnos.actualizarCola();
        consultarTurnos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bttConsultaTurnosActionPerformed

    private void bttAtendidosRecienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAtendidosRecienActionPerformed
        // TODO add your handling code here:
        historialAtendidos.recibiratendidos(atendidos);
        historialAtendidos.actualizarpila();
        historialAtendidos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bttAtendidosRecienActionPerformed

    private void bttConsultaPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttConsultaPacientesActionPerformed

        consultarHistorial.recibirCola(turnos);
        consultarHistorial.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bttConsultaPacientesActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        actualizarDatos.recibirColaPacientes(turnos);
        actualizarDatos.recibirMenu(this);
        actualizarDatos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnImportarexcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarexcelActionPerformed
        File archivoImportado = AdministradorExcel.seleccionarArchivoExcel();
        if (archivoImportado == null) {
            JOptionPane.showMessageDialog(null, "No se selecciono ningun archivo");
        } else {
            ListaSimple lista = AdministradorExcel.importarPacientes(archivoImportado);
            Nodo aux = lista.getPrimero();
            while(aux != null){
                Paciente pa = (Paciente)(aux.getDato());
                if (pa.isAtendido()) {
                    atendidos.Apilar(pa);
                }
                aux = aux.getSiguiente();
            }
            while (lista.getPrimero() != null) {
                turnos.EncolarPrioridad(lista.getPrimero().getDato());
                lista.EliminarP();
            }
            JOptionPane.showMessageDialog(null, "Archivo seleccionado con exito");
        }
    }//GEN-LAST:event_btnImportarexcelActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        // TODO add your handling code here:
        File archivoExportar = AdministradorExcel.seleccionarRutaParaGuardar();
        if (archivoExportar == null) {
            JOptionPane.showMessageDialog(null, "No se selecciono ningun archivo");
        } else {
            Lista_Doble listaExportar = new Lista_Doble();
            Nodo aux = atendidos.getCima();
            while(aux != null){
                listaExportar.InsertarUltimo(aux.getDato());
                aux = aux.getSiguiente();
            }
            AdministradorExcel.exportarEstudiantes(listaExportar, archivoExportar);
            JOptionPane.showMessageDialog(null, "Datos exportados con exito");
        }
    }//GEN-LAST:event_btnExportarActionPerformed

    public void recibirTurnos(Cola c) {
        // Recibir la cola de turnos actualizada
        turnos = c;
    }

    public void recibiratendidos(Pila p) {
        // Recibir la pila de atendidos actualizada
        atendidos = p;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnImportarexcel;
    private javax.swing.JButton bttAtendidosRecien;
    private javax.swing.JButton bttConsultaPacientes;
    private javax.swing.JButton bttConsultaTurnos;
    private javax.swing.JButton bttRegistro;
    private javax.swing.JLabel labelHospital;
    // End of variables declaration//GEN-END:variables
     // Atributos globales 
    Registrar registrar;
    consultarTurnos consultarTurnos;
    consultarHistorialPaciente consultarHistorial;
    historialAtendidos historialAtendidos;
    actualizarDatos actualizarDatos;
    Cola turnos = new Cola();
    Pila atendidos = new Pila();
//    Lista_Doble historial = new Lista_Doble();
}
